version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "dev"
    labels:
      - "go dependencies"
    reviewers:
      - beyazit
